apiVersion: v1
kind: Namespace
metadata:
  name: pnp-ltim-thulasiram-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnp-ltim-thulasiram-deployment
  namespace: pnp-ltim-thulasiram-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/cisco_pov:60a28bb9e9b2dbe8f6d7d718b9837db55d651ca2

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pnp-ltim-thulasiram-label
  name: pnp-ltim-thulasiram-service
  namespace: pnp-ltim-thulasiram-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---